version: "3"
services:

  test:
    container_name: thomas-blog-test
    command: jekyll serve
    image: jekyll/jekyll
    volumes:
      - $PWD:/srv/jekyll
    ports:
      -   4000:4000

  build:
    container_name: thomas-blog-build
    command: jekyll build
    image: jekyll/jekyll
    volumes:
      - $PWD:/srv/jekyll

